# Generated by Django 5.0.4 on 2024-05-16 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('create_date',)},
        ),
    ]
