# Generated by Django 5.0.4 on 2024-05-16 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0002_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reviews',
            options={'ordering': ('-create_date',)},
        ),
    ]
