# Generated by Django 5.0.4 on 2024-05-27 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0003_alter_reviews_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reply',
            options={'ordering': ('time_create',), 'verbose_name': 'Ответ', 'verbose_name_plural': 'Ответы'},
        ),
    ]
