# Generated by Django 5.0.4 on 2024-06-27 18:13

import components.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0007_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=components.utils.category_image_path),
        ),
    ]
