# Generated by Django 5.0.4 on 2024-06-28 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0009_order_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='end_date',
        ),
    ]
