# Generated by Django 5.0.4 on 2024-06-29 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_remove_order_end_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('1', 'Ждёт отправки'), ('2', 'В пути'), ('3', 'Доставлен')], max_length=50),
        ),
    ]
